site_name: 'Pygame Multi — Documentación'
theme:
  name: material
  language: es
  palette:
    - scheme: slate
      primary: deep purple
      accent: amber
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Inicio: index.md
  - Diagramas:
    - diagramas/index.md
    - Clases: diagramas/clases.md
    - Paso de Mensajes: diagramas/mensajes.md
    - Estados y Condiciones: diagramas/estados.md
    - ServerState & ClientState: diagramas/server-client.md
